Fixing proc params for equipped (#2784)
<!-- Write **BELOW** The Headers and **ABOVE** The comments else it may
not be viewable. -->

## About The Pull Request
Adds the two proc params to some calls I forgot earlier. These might fix
some of the runtimes that show up. I'm not sure but the two examples I
<!-- Describe The Pull Request. Please be sure every change is
documented or this can delay review and even discourage maintainers from
merging your PR! -->

## Why It's Good For The Game
runtimes are bad.
<!-- Argue for the merits of your changes and how they benefit the game,
especially if they are controversial and/or far reaching. If you can't
actually explain WHY what you are doing will improve the game, then it
probably isn't good for the game in the first place. -->


## Proof of Testing (Required)
I don't really have proof but hopefully it should stop any `runtime
error: bad arg name 'silent'` from showing up now.

The two examples I did see seemed to be right clicking keyrings off the
floor, which I think went through the not_handled statement and
spectacles equip and I can't get them to runtime when I tried.

![image](https://github.com/user-attachments/assets/f96b20cb-d8cc-4eef-ba8f-9ef982df5e25)

<!-- Show proof of testing, screenshots or recordings for features,
proof of compile for backend changes -->